services:
  gonolith1:
    image: gonolith
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
      - "7946:7946"
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=50051
      - NODE_NAME=gonolith1
      - CLUSTER_MEMBERS=gonolith2:7946

  gonolith2:
    image: gonolith
    ports:
      - "8081:8080"
      - "50052:50051"
      - "7947:7946"
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=50051
      - NODE_NAME=gonolith2
      - CLUSTER_MEMBERS=gonolith1:7946
